### ISSUE TITLE
Promises should use $q in angular 

### ISSUE THREAD

**Issue by fotoflo** [slively/angular-dpd#6]
Would be awesome if we could switch to $q promises for the angular implementation.

**Comment by slively** [comment]
I haven't used this library in a while, but I still merge pull requests if you want to give it a tru.

**Comment by fotoflo** [comment]
Thanks Scott, After discussion on https://gitter.im/deployd/deployd with @andreialecu, I learned that we use the same $http promises, so this is not necessary. 

I also did some experimentation and found that it is possible to use $

**Comment by slively** [comment]
awesome!
